'use client'

import { useState, useEffect, useRef } from 'react'
import { ModuleResponse, LearningGoalResponse } from '@/lib/types/api'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Label } from '@/components/ui/label'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { useCoursesStore } from '@/lib/stores/courses-store'
import {
  useUpdateModule,
  useGenerateOverview,
  useLearningGoals,
  useCreateLearningGoal,
  useUpdateLearningGoal,
  useDeleteLearningGoal,
  useGenerateLearningGoals,
} from '@/lib/hooks/use-modules'
import { Plus, X, Sparkles, Loader2 } from 'lucide-react'

interface ModuleDetailsProps {
  module: ModuleResponse
  canEdit?: boolean
}

export function ModuleDetails({ module, canEdit = true }: ModuleDetailsProps) {
  const updateModule = useUpdateModule()
  const generateOverview = useGenerateOverview()
  const { getModuleMetadata, updateModuleMetadata } = useCoursesStore()

  // Learning goals hooks
  const { data: learningGoals = [], isLoading: isLoadingGoals } = useLearningGoals(module.id)
  const createLearningGoal = useCreateLearningGoal()
  const updateLearningGoal = useUpdateLearningGoal()
  const deleteLearningGoal = useDeleteLearningGoal()
  const generateLearningGoals = useGenerateLearningGoals()

  // Local state for editing goals (tracks which goal is being edited and its current value)
  const [editingGoals, setEditingGoals] = useState<Record<string, string>>({})

  const metadata = getModuleMetadata(module.id)
  // Use overview from API (module.overview) as primary source, fall back to local store
  const [overview, setOverview] = useState(module.overview || metadata.overview || '')
  const [dueDate, setDueDate] = useState(metadata.dueDate || '')
  const [prerequisites, setPrerequisites] = useState(metadata.prerequisites || '')

  // Track if we've already attempted to auto-generate for this module
  const hasAutoGeneratedOverview = useRef<string | null>(null)
  const hasAutoGeneratedGoals = useRef<string | null>(null)

  // Auto-generate overview when page loads if no overview exists
  useEffect(() => {
    if (!canEdit) return
    if (
      module.id &&
      !module.overview &&
      !generateOverview.isPending &&
      hasAutoGeneratedOverview.current !== module.id
    ) {
      hasAutoGeneratedOverview.current = module.id
      generateOverview.mutate(
        { id: module.id },
        {
          onSuccess: (updatedModule) => {
            if (updatedModule.overview) {
              setOverview(updatedModule.overview)
            }
          },
        }
      )
    }
  }, [module.id, module.overview, generateOverview, canEdit])

  // Auto-generate learning goals when page loads if no goals exist
  useEffect(() => {
    if (!canEdit) return
    if (
      module.id &&
      !isLoadingGoals &&
      learningGoals.length === 0 &&
      !generateLearningGoals.isPending &&
      hasAutoGeneratedGoals.current !== module.id
    ) {
      hasAutoGeneratedGoals.current = module.id
      generateLearningGoals.mutate({ id: module.id })
    }
  }, [module.id, isLoadingGoals, learningGoals.length, generateLearningGoals, canEdit])

  // Sync overview state when module.overview changes (e.g., after generation)
  useEffect(() => {
    if (module.overview && module.overview !== overview) {
      setOverview(module.overview)
    }
  }, [module.overview])

  // Initialize editing state when goals load
  useEffect(() => {
    const newEditingState: Record<string, string> = {}
    learningGoals.forEach((goal) => {
      if (!(goal.id in editingGoals)) {
        newEditingState[goal.id] = goal.description
      }
    })
    if (Object.keys(newEditingState).length > 0) {
      setEditingGoals((prev) => ({ ...prev, ...newEditingState }))
    }
  }, [learningGoals])

  const handleSaveOverview = () => {
    if (!canEdit) return
    // Save to backend
    updateModule.mutate({
      id: module.id,
      data: { overview },
    })
    // Also save to local store for backwards compatibility
    updateModuleMetadata(module.id, { overview })
  }

  const handleRegenerateOverview = () => {
    if (!canEdit) return
    generateOverview.mutate(
      { id: module.id },
      {
        onSuccess: (updatedModule) => {
          if (updatedModule.overview) {
            setOverview(updatedModule.overview)
          }
        },
      }
    )
  }

  const handleRegenerateLearningGoals = () => {
    if (!canEdit) return
    generateLearningGoals.mutate({ id: module.id })
  }

  const handleSaveDueDate = () => {
    if (!canEdit) return
    updateModuleMetadata(module.id, { dueDate })
  }

  const handleSavePrerequisites = () => {
    if (!canEdit) return
    updateModuleMetadata(module.id, { prerequisites })
  }

  const handleAddLearningGoal = () => {
    if (!canEdit) return
    createLearningGoal.mutate({
      moduleId: module.id,
      data: { description: 'New learning goal' },
    })
  }

  const handleUpdateLearningGoalDescription = (goal: LearningGoalResponse) => {
    if (!canEdit) return
    const newDescription = editingGoals[goal.id]
    if (newDescription && newDescription !== goal.description) {
      updateLearningGoal.mutate({
        goalId: goal.id,
        moduleId: module.id,
        data: { description: newDescription },
      })
    }
  }

  const handleDeleteLearningGoal = (goalId: string) => {
    if (!canEdit) return
    deleteLearningGoal.mutate({ goalId, moduleId: module.id })
  }

  const isGeneratingGoals = generateLearningGoals.isPending

  return (
    <div className="space-y-6">
      {/* Module Information Section */}
      <Card>
        <CardHeader>
          <CardTitle>Module Information</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="module-name">Name</Label>
            <Input
              id="module-name"
              value={module.name}
              onChange={(e) => {
                if (!canEdit) return
                updateModule.mutate({
                  id: module.id,
                  data: { name: e.target.value },
                })
              }}
              placeholder="Module name"
              readOnly={!canEdit}
            />
          </div>

          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <Label htmlFor="module-overview">Overview</Label>
              {canEdit && (
                <Button
                  type="button"
                  variant="outline"
                  size="sm"
                  onClick={handleRegenerateOverview}
                  disabled={generateOverview.isPending}
                >
                  {generateOverview.isPending ? (
                    <>
                      <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                      Generating...
                    </>
                  ) : (
                    <>
                      <Sparkles className="h-4 w-4 mr-2" />
                      Regenerate
                    </>
                  )}
                </Button>
              )}
            </div>
            <Textarea
              id="module-overview"
              value={overview}
              onChange={(e) => setOverview(e.target.value)}
              onBlur={handleSaveOverview}
              placeholder={generateOverview.isPending ? "Generating overview..." : "Enter module overview..."}
              rows={6}
              disabled={generateOverview.isPending || !canEdit}
              readOnly={!canEdit}
            />
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="module-due-date">Due Date</Label>
              <Input
                id="module-due-date"
                type="date"
                value={dueDate}
                onChange={(e) => setDueDate(e.target.value)}
                onBlur={handleSaveDueDate}
                disabled={!canEdit}
                readOnly={!canEdit}
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="module-prerequisites">Prerequisites</Label>
              <Input
                id="module-prerequisites"
                value={prerequisites}
                onChange={(e) => setPrerequisites(e.target.value)}
                onBlur={handleSavePrerequisites}
                placeholder="e.g., CS 101, MATH 201"
                disabled={!canEdit}
                readOnly={!canEdit}
              />
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Learning Goals Section */}
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <CardTitle>Learning Goals</CardTitle>
            {canEdit && (
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={handleRegenerateLearningGoals}
                disabled={isGeneratingGoals}
              >
                {isGeneratingGoals ? (
                  <>
                    <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    <Sparkles className="h-4 w-4 mr-2" />
                    Regenerate
                  </>
                )}
              </Button>
            )}
          </div>
        </CardHeader>
        <CardContent className="space-y-4">
          {isLoadingGoals || isGeneratingGoals ? (
            <div className="flex items-center justify-center py-4 text-muted-foreground">
              <Loader2 className="h-4 w-4 mr-2 animate-spin" />
              {isGeneratingGoals ? 'Generating learning goals...' : 'Loading...'}
            </div>
          ) : learningGoals.length === 0 ? (
            <p className="text-sm text-muted-foreground">
              No learning goals yet. Click &quot;Add Learning Goal&quot; to get started.
            </p>
          ) : (
            <div className="space-y-3">
              {learningGoals.map((goal) => (
                <div key={goal.id} className="flex items-start gap-2">
                  <Input
                    value={editingGoals[goal.id] ?? goal.description}
                    onChange={(e) =>
                      setEditingGoals((prev) => ({
                        ...prev,
                        [goal.id]: e.target.value,
                      }))
                    }
                    onBlur={() => handleUpdateLearningGoalDescription(goal)}
                    placeholder="Learning goal description"
                    className="flex-1"
                    readOnly={!canEdit}
                    disabled={!canEdit}
                  />
                  {canEdit && (
                    <Button
                      type="button"
                      variant="ghost"
                      size="sm"
                      onClick={() => handleDeleteLearningGoal(goal.id)}
                      className="h-10 w-10 p-0"
                    >
                      <X className="h-4 w-4" />
                    </Button>
                  )}
                </div>
              ))}
            </div>
          )}
          {canEdit && (
            <Button
              type="button"
              variant="outline"
              onClick={handleAddLearningGoal}
              className="w-full"
              disabled={createLearningGoal.isPending || isGeneratingGoals}
            >
              <Plus className="h-4 w-4 mr-2" />
              Add Learning Goal
            </Button>
          )}
        </CardContent>
      </Card>
    </div>
  )
}
