'use client'

import { useState, useEffect, useRef } from 'react'
import { useQueryClient } from '@tanstack/react-query'
import { ModuleResponse, LearningGoalResponse } from '@/lib/types/api'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { MarkdownViewEdit } from '@/components/ui/markdown-view-edit'
import { CompetencyList, parseCompetencies } from '@/components/ui/competency-list'
import { useCoursesStore } from '@/lib/stores/courses-store'
import { modulesApi } from '@/lib/api/modules'
import { QUERY_KEYS } from '@/lib/api/query-client'
import {
  useUpdateModule,
  useGenerateOverview,
  useLearningGoals,
  useCreateLearningGoal,
  useUpdateLearningGoal,
  useDeleteLearningGoal,
  useGenerateLearningGoals,
} from '@/lib/hooks/use-modules'
import { Plus, X, Sparkles, Loader2, ChevronDown } from 'lucide-react'
import { cn } from '@/lib/utils'
import { RefinementChat } from '@/components/modules/RefinementChat'
import { LearningGoalPreview } from '@/lib/types/api'

interface ModuleDetailsProps {
  module: ModuleResponse
  canEdit?: boolean
}

export function ModuleDetails({ module, canEdit = true }: ModuleDetailsProps) {
  const queryClient = useQueryClient()
  const updateModule = useUpdateModule()
  const generateOverview = useGenerateOverview()
  const { getModuleMetadata, updateModuleMetadata } = useCoursesStore()

  // Learning goals hooks
  const { data: learningGoals = [], isLoading: isLoadingGoals } = useLearningGoals(module.id)
  const createLearningGoal = useCreateLearningGoal()
  const updateLearningGoal = useUpdateLearningGoal()
  const deleteLearningGoal = useDeleteLearningGoal()
  const generateLearningGoals = useGenerateLearningGoals()

  // Local state for editing goals
  const [editingGoals, setEditingGoals] = useState<Record<string, { description: string; title: string; takeaways: string; competencies: string }>>({})
  const [expandedGoalId, setExpandedGoalId] = useState<string | null>(null)

  // Per-section pulse state for AI refinement animation
  const [refinePulse, setRefinePulse] = useState<{ overview: boolean; goalIndices: Set<number> }>({ overview: false, goalIndices: new Set() })
  const refinePulseTimeout = useRef<ReturnType<typeof setTimeout> | null>(null)

  const triggerRefinePulse = (overview: boolean, goalIndices: Set<number>) => {
    if (refinePulseTimeout.current) clearTimeout(refinePulseTimeout.current)
    setRefinePulse({ overview, goalIndices })
    refinePulseTimeout.current = setTimeout(() => setRefinePulse({ overview: false, goalIndices: new Set() }), 1600)
  }

  const metadata = getModuleMetadata(module.id)
  // Use overview from API (module.overview) as primary source, fall back to local store
  const [overview, setOverview] = useState(module.overview || metadata.overview || '')
  const [dueDate, setDueDate] = useState(metadata.dueDate || '')
  const [prerequisites, setPrerequisites] = useState(metadata.prerequisites || '')

  // Track if we've already attempted to auto-generate for this module
  const hasAutoGeneratedOverview = useRef<string | null>(null)
  const hasAutoGeneratedGoals = useRef<string | null>(null)

  // Auto-generate overview when page loads if no overview exists
  useEffect(() => {
    if (!canEdit) return
    if (
      module.id &&
      !module.overview &&
      !generateOverview.isPending &&
      hasAutoGeneratedOverview.current !== module.id
    ) {
      hasAutoGeneratedOverview.current = module.id
      generateOverview.mutate(
        { module_id: module.id },
        {
          onSuccess: (data) => {
            if (data.overview) {
              setOverview(data.overview)
            }
          },
        }
      )
    }
  }, [module.id, module.overview, generateOverview, canEdit])

  // Auto-generate learning goals when page loads if no goals exist
  useEffect(() => {
    if (!canEdit) return
    if (
      module.id &&
      !isLoadingGoals &&
      learningGoals.length === 0 &&
      !generateLearningGoals.isPending &&
      hasAutoGeneratedGoals.current !== module.id
    ) {
      hasAutoGeneratedGoals.current = module.id
      generateLearningGoals.mutate({ module_id: module.id })
    }
  }, [module.id, isLoadingGoals, learningGoals.length, generateLearningGoals, canEdit])

  // Sync overview state when module.overview changes (e.g., after generation)
  useEffect(() => {
    if (module.overview && module.overview !== overview) {
      setOverview(module.overview)
    }
  }, [module.overview])

  // Initialize editing state when goals load
  useEffect(() => {
    const newEditingState: Record<string, { description: string; title: string; takeaways: string; competencies: string }> = {}
    learningGoals.forEach((goal) => {
      if (!(goal.id in editingGoals)) {
        newEditingState[goal.id] = {
          description: goal.description,
          title: goal.title || '',
          takeaways: goal.takeaways || '',
          competencies: goal.competencies || '',
        }
      }
    })
    if (Object.keys(newEditingState).length > 0) {
      setEditingGoals((prev) => ({ ...prev, ...newEditingState }))
    }
  }, [learningGoals])

  const handleSaveOverview = () => {
    if (!canEdit) return
    // Save to backend
    updateModule.mutate({
      id: module.id,
      data: { overview },
    })
    // Also save to local store for backwards compatibility
    updateModuleMetadata(module.id, { overview })
  }

  const handleRegenerateOverview = () => {
    if (!canEdit) return
    generateOverview.mutate(
      { module_id: module.id },
      {
        onSuccess: (data) => {
          if (data.overview) {
            setOverview(data.overview)
          }
        },
      }
    )
  }

  const handleRegenerateLearningGoals = () => {
    if (!canEdit) return
    generateLearningGoals.mutate({ module_id: module.id })
  }

  const handleSaveDueDate = () => {
    if (!canEdit) return
    updateModuleMetadata(module.id, { dueDate })
  }

  const handleSavePrerequisites = () => {
    if (!canEdit) return
    updateModuleMetadata(module.id, { prerequisites })
  }

  const handleAddLearningGoal = () => {
    if (!canEdit) return
    createLearningGoal.mutate({
      moduleId: module.id,
      data: { description: 'New learning goal' },
    })
  }

  const handleUpdateLearningGoal = (goal: LearningGoalResponse) => {
    if (!canEdit) return
    const editing = editingGoals[goal.id]
    if (!editing) return
    const updates: Record<string, string> = {}
    if (editing.description !== goal.description) updates.description = editing.description
    if (editing.title !== (goal.title || '')) updates.title = editing.title
    if (editing.takeaways !== (goal.takeaways || '')) updates.takeaways = editing.takeaways
    if (editing.competencies !== (goal.competencies || '')) updates.competencies = editing.competencies
    if (Object.keys(updates).length > 0) {
      updateLearningGoal.mutate({
        goalId: goal.id,
        moduleId: module.id,
        data: updates,
      })
    }
  }

  const handleDeleteLearningGoal = (goalId: string) => {
    if (!canEdit) return
    deleteLearningGoal.mutate({ goalId, moduleId: module.id })
  }

  const handleRefinementApply = async (newOverview: string, newGoals: LearningGoalPreview[]) => {
    if (!canEdit) return

    const normalize = (s: string) => (s || '').trim().replace(/\s+/g, ' ')
    const overviewChanged = normalize(newOverview) !== normalize(overview)
    const changedGoalIndices = new Set<number>()
    newGoals.forEach((g, i) => {
      const existing = learningGoals[i]
      if (
        !existing ||
        g.description !== existing.description ||
        (g.takeaways || '') !== (existing.takeaways || '') ||
        (g.competencies || '') !== (existing.competencies || '')
      ) {
        changedGoalIndices.add(i)
      }
    })

    // Update overview
    setOverview(newOverview)
    updateModule.mutate({ id: module.id, data: { overview: newOverview } })
    updateModuleMetadata(module.id, { overview: newOverview })

    // Replace learning goals: delete existing, create new
    for (const goal of learningGoals) {
      await modulesApi.deleteLearningGoal(goal.id)
    }
    for (let i = 0; i < newGoals.length; i++) {
      await modulesApi.createLearningGoal(module.id, {
        description: newGoals[i].description,
        title: newGoals[i].title || undefined,
        takeaways: newGoals[i].takeaways,
        competencies: newGoals[i].competencies,
        order: i,
      })
    }

    // Refresh the learning goals query
    queryClient.invalidateQueries({ queryKey: QUERY_KEYS.learningGoals(module.id) })

    triggerRefinePulse(overviewChanged, changedGoalIndices)
  }

  const isGeneratingGoals = generateLearningGoals.isPending

  return (
    <div className="space-y-6">
      {/* Module Information Section */}
      <Card>
        <CardHeader>
          <CardTitle>Module Information</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="module-name">Name</Label>
            <Input
              id="module-name"
              value={module.name}
              onChange={(e) => {
                if (!canEdit) return
                updateModule.mutate({
                  id: module.id,
                  data: { name: e.target.value },
                })
              }}
              placeholder="Module name"
              readOnly={!canEdit}
            />
          </div>

          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <Label htmlFor="module-overview">Overview</Label>
              {canEdit && (
                <Button
                  type="button"
                  variant="outline"
                  size="sm"
                  onClick={handleRegenerateOverview}
                  disabled={generateOverview.isPending}
                >
                  {generateOverview.isPending ? (
                    <>
                      <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                      Generating...
                    </>
                  ) : (
                    <>
                      <Sparkles className="h-4 w-4 mr-2" />
                      Regenerate
                    </>
                  )}
                </Button>
              )}
            </div>
            <MarkdownViewEdit
              value={overview}
              onChange={setOverview}
              onBlur={handleSaveOverview}
              placeholder={generateOverview.isPending ? "Generating overview..." : "Enter module overview..."}
              disabled={generateOverview.isPending || !canEdit}
              readOnly={!canEdit}
              minHeight="120px"
              className={cn(refinePulse.overview && 'animate-border-pulse')}
            />
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="module-due-date">Due Date</Label>
              <Input
                id="module-due-date"
                type="date"
                value={dueDate}
                onChange={(e) => setDueDate(e.target.value)}
                onBlur={handleSaveDueDate}
                disabled={!canEdit}
                readOnly={!canEdit}
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="module-prerequisites">Prerequisites</Label>
              <Input
                id="module-prerequisites"
                value={prerequisites}
                onChange={(e) => setPrerequisites(e.target.value)}
                onBlur={handleSavePrerequisites}
                placeholder="e.g., CS 101, MATH 201"
                disabled={!canEdit}
                readOnly={!canEdit}
              />
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Learning Goals Section */}
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <CardTitle>Learning Goals</CardTitle>
            {canEdit && (
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={handleRegenerateLearningGoals}
                disabled={isGeneratingGoals}
              >
                {isGeneratingGoals ? (
                  <>
                    <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    <Sparkles className="h-4 w-4 mr-2" />
                    Regenerate
                  </>
                )}
              </Button>
            )}
          </div>
        </CardHeader>
        <CardContent className="space-y-4">
          {isLoadingGoals || isGeneratingGoals ? (
            <div className="flex items-center justify-center py-4 text-muted-foreground">
              <Loader2 className="h-4 w-4 mr-2 animate-spin" />
              {isGeneratingGoals ? 'Generating learning goals...' : 'Loading...'}
            </div>
          ) : learningGoals.length === 0 ? (
            <p className="text-sm text-muted-foreground">
              No learning goals yet. Click &quot;Add Learning Goal&quot; to get started.
            </p>
          ) : (
            <div className="space-y-3">
              {learningGoals.map((goal, goalIdx) => {
                const isExpanded = expandedGoalId === goal.id
                const editing = editingGoals[goal.id]
                return (
                  <div
                    key={goal.id}
                    className={cn(
                      'border rounded-lg overflow-hidden transition-all',
                      isExpanded && 'bg-muted/30',
                      refinePulse.goalIndices.has(goalIdx) && 'animate-border-pulse'
                    )}
                  >
                    {/* Header row */}
                    <div
                      className={cn(
                        'flex items-center gap-2 p-3 cursor-pointer transition-colors',
                        !isExpanded && 'hover:bg-secondary/50'
                      )}
                      onClick={() => setExpandedGoalId(isExpanded ? null : goal.id)}
                    >
                      <ChevronDown
                        className={cn(
                          'h-4 w-4 text-muted-foreground transition-transform flex-shrink-0',
                          isExpanded && 'rotate-180'
                        )}
                      />
                      {isExpanded ? (
                        <Input
                          value={editing?.title ?? goal.title ?? ''}
                          onChange={(e) =>
                            setEditingGoals((prev) => ({
                              ...prev,
                              [goal.id]: { ...(prev[goal.id] || { description: goal.description, title: goal.title || '', takeaways: goal.takeaways || '', competencies: goal.competencies || '' }), title: e.target.value },
                            }))
                          }
                          onBlur={() => handleUpdateLearningGoal(goal)}
                          onClick={(e) => e.stopPropagation()}
                          placeholder="Short title (e.g. Logistic Regression)"
                          className="flex-1 font-medium"
                          readOnly={!canEdit}
                          disabled={!canEdit}
                        />
                      ) : (
                        <div className="flex-1 min-w-0">
                          <span className="block text-sm font-medium truncate">
                            {editing?.title || goal.title || editing?.description || goal.description || 'Untitled goal'}
                          </span>
                          <div className="flex items-center gap-2 mt-0.5">
                            {(editing?.description || goal.description) && (
                              <span className="text-[11px] text-muted-foreground italic truncate">
                                {editing?.description || goal.description}
                              </span>
                            )}
                            {parseCompetencies(editing?.competencies || goal.competencies || '').length > 0 && (
                              <Badge
                                variant="secondary"
                                className="flex-shrink-0 text-[11px] px-1.5 py-0 h-4 font-normal text-muted-foreground"
                              >
                                {parseCompetencies(editing?.competencies || goal.competencies || '').length}{' '}
                                {parseCompetencies(editing?.competencies || goal.competencies || '').length === 1 ? 'competency' : 'competencies'}
                              </Badge>
                            )}
                          </div>
                        </div>
                      )}
                      {canEdit && (
                        <Button
                          type="button"
                          variant="ghost"
                          size="sm"
                          onClick={(e) => {
                            e.stopPropagation()
                            handleDeleteLearningGoal(goal.id)
                          }}
                          className="h-8 w-8 p-0 flex-shrink-0"
                        >
                          <X className="h-4 w-4" />
                        </Button>
                      )}
                    </div>

                    {/* Expanded content: title, takeaways & competencies */}
                    {isExpanded && (
                      <div className="px-6 pb-4 space-y-4">
                        <div className="space-y-2">
                          <Label className="text-xs font-medium uppercase text-muted-foreground">
                            Description
                          </Label>
                          <Input
                            value={editing?.description ?? goal.description}
                            onChange={(e) =>
                              setEditingGoals((prev) => ({
                                ...prev,
                                [goal.id]: { ...(prev[goal.id] || { description: goal.description, title: goal.title || '', takeaways: goal.takeaways || '', competencies: goal.competencies || '' }), description: e.target.value },
                              }))
                            }
                            onBlur={() => handleUpdateLearningGoal(goal)}
                            placeholder="Full description of this learning goal..."
                            readOnly={!canEdit}
                            disabled={!canEdit}
                          />
                        </div>
                        <div className="space-y-2">
                          <Label className="text-xs font-medium uppercase text-muted-foreground">
                            Takeaways
                          </Label>
                          <MarkdownViewEdit
                            value={editing?.takeaways ?? goal.takeaways ?? ''}
                            onChange={(val) =>
                              setEditingGoals((prev) => ({
                                ...prev,
                                [goal.id]: { ...(prev[goal.id] || { description: goal.description, takeaways: goal.takeaways || '', competencies: goal.competencies || '' }), takeaways: val },
                              }))
                            }
                            onBlur={() => handleUpdateLearningGoal(goal)}
                            placeholder="Key concepts or skills to be learned..."
                            readOnly={!canEdit}
                            disabled={!canEdit}
                            minHeight="60px"
                          />
                        </div>
                        <div className="space-y-2">
                          <Label className="text-xs font-medium uppercase text-muted-foreground">
                            Competencies
                          </Label>
                          <CompetencyList
                            value={editing?.competencies ?? goal.competencies ?? ''}
                            onChange={(val) =>
                              setEditingGoals((prev) => ({
                                ...prev,
                                [goal.id]: { ...(prev[goal.id] || { description: goal.description, takeaways: goal.takeaways || '', competencies: goal.competencies || '' }), competencies: val },
                              }))
                            }
                            onBlur={() => handleUpdateLearningGoal(goal)}
                            placeholder="Abilities to apply learned concepts..."
                            readOnly={!canEdit}
                            disabled={!canEdit}
                          />
                        </div>
                      </div>
                    )}
                  </div>
                )
              })}
            </div>
          )}
          {canEdit && (
            <Button
              type="button"
              variant="outline"
              onClick={handleAddLearningGoal}
              className="w-full"
              disabled={createLearningGoal.isPending || isGeneratingGoals}
            >
              <Plus className="h-4 w-4 mr-2" />
              Add Learning Goal
            </Button>
          )}
        </CardContent>
      </Card>

      {/* Refinement Chat */}
      {canEdit && (
        <RefinementChat
          currentOverview={overview}
          currentGoals={learningGoals.map((g) => ({
            title: g.title || '',
            description: g.description,
            takeaways: g.takeaways || '',
            competencies: g.competencies || '',
          }))}
          onApplyChanges={handleRefinementApply}
          moduleId={module.id}
        />
      )}
    </div>
  )
}
