'use client'

import { useState, useEffect, useRef } from 'react'
import { ModuleResponse, LearningGoalResponse } from '@/lib/types/api'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Label } from '@/components/ui/label'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { useCoursesStore } from '@/lib/stores/courses-store'
import {
  useUpdateModule,
  useGenerateOverview,
  useLearningGoals,
  useCreateLearningGoal,
  useUpdateLearningGoal,
  useDeleteLearningGoal,
  useGenerateLearningGoals,
} from '@/lib/hooks/use-modules'
import { Plus, X, Sparkles, Loader2, ChevronDown } from 'lucide-react'
import { cn } from '@/lib/utils'

interface ModuleDetailsProps {
  module: ModuleResponse
  canEdit?: boolean
}

export function ModuleDetails({ module, canEdit = true }: ModuleDetailsProps) {
  const updateModule = useUpdateModule()
  const generateOverview = useGenerateOverview()
  const { getModuleMetadata, updateModuleMetadata } = useCoursesStore()

  // Learning goals hooks
  const { data: learningGoals = [], isLoading: isLoadingGoals } = useLearningGoals(module.id)
  const createLearningGoal = useCreateLearningGoal()
  const updateLearningGoal = useUpdateLearningGoal()
  const deleteLearningGoal = useDeleteLearningGoal()
  const generateLearningGoals = useGenerateLearningGoals()

  // Local state for editing goals
  const [editingGoals, setEditingGoals] = useState<Record<string, { description: string; takeaways: string; competencies: string }>>({})
  const [expandedGoalId, setExpandedGoalId] = useState<string | null>(null)

  const metadata = getModuleMetadata(module.id)
  // Use overview from API (module.overview) as primary source, fall back to local store
  const [overview, setOverview] = useState(module.overview || metadata.overview || '')
  const [dueDate, setDueDate] = useState(metadata.dueDate || '')
  const [prerequisites, setPrerequisites] = useState(metadata.prerequisites || '')

  // Track if we've already attempted to auto-generate for this module
  const hasAutoGeneratedOverview = useRef<string | null>(null)
  const hasAutoGeneratedGoals = useRef<string | null>(null)

  // Auto-generate overview when page loads if no overview exists
  useEffect(() => {
    if (!canEdit) return
    if (
      module.id &&
      !module.overview &&
      !generateOverview.isPending &&
      hasAutoGeneratedOverview.current !== module.id
    ) {
      hasAutoGeneratedOverview.current = module.id
      generateOverview.mutate(
        { module_id: module.id },
        {
          onSuccess: (data) => {
            if (data.overview) {
              setOverview(data.overview)
            }
          },
        }
      )
    }
  }, [module.id, module.overview, generateOverview, canEdit])

  // Auto-generate learning goals when page loads if no goals exist
  useEffect(() => {
    if (!canEdit) return
    if (
      module.id &&
      !isLoadingGoals &&
      learningGoals.length === 0 &&
      !generateLearningGoals.isPending &&
      hasAutoGeneratedGoals.current !== module.id
    ) {
      hasAutoGeneratedGoals.current = module.id
      generateLearningGoals.mutate({ module_id: module.id })
    }
  }, [module.id, isLoadingGoals, learningGoals.length, generateLearningGoals, canEdit])

  // Sync overview state when module.overview changes (e.g., after generation)
  useEffect(() => {
    if (module.overview && module.overview !== overview) {
      setOverview(module.overview)
    }
  }, [module.overview])

  // Initialize editing state when goals load
  useEffect(() => {
    const newEditingState: Record<string, { description: string; takeaways: string; competencies: string }> = {}
    learningGoals.forEach((goal) => {
      if (!(goal.id in editingGoals)) {
        newEditingState[goal.id] = {
          description: goal.description,
          takeaways: goal.takeaways || '',
          competencies: goal.competencies || '',
        }
      }
    })
    if (Object.keys(newEditingState).length > 0) {
      setEditingGoals((prev) => ({ ...prev, ...newEditingState }))
    }
  }, [learningGoals])

  const handleSaveOverview = () => {
    if (!canEdit) return
    // Save to backend
    updateModule.mutate({
      id: module.id,
      data: { overview },
    })
    // Also save to local store for backwards compatibility
    updateModuleMetadata(module.id, { overview })
  }

  const handleRegenerateOverview = () => {
    if (!canEdit) return
    generateOverview.mutate(
      { module_id: module.id },
      {
        onSuccess: (data) => {
          if (data.overview) {
            setOverview(data.overview)
          }
        },
      }
    )
  }

  const handleRegenerateLearningGoals = () => {
    if (!canEdit) return
    generateLearningGoals.mutate({ module_id: module.id })
  }

  const handleSaveDueDate = () => {
    if (!canEdit) return
    updateModuleMetadata(module.id, { dueDate })
  }

  const handleSavePrerequisites = () => {
    if (!canEdit) return
    updateModuleMetadata(module.id, { prerequisites })
  }

  const handleAddLearningGoal = () => {
    if (!canEdit) return
    createLearningGoal.mutate({
      moduleId: module.id,
      data: { description: 'New learning goal' },
    })
  }

  const handleUpdateLearningGoal = (goal: LearningGoalResponse) => {
    if (!canEdit) return
    const editing = editingGoals[goal.id]
    if (!editing) return
    const updates: Record<string, string> = {}
    if (editing.description !== goal.description) updates.description = editing.description
    if (editing.takeaways !== (goal.takeaways || '')) updates.takeaways = editing.takeaways
    if (editing.competencies !== (goal.competencies || '')) updates.competencies = editing.competencies
    if (Object.keys(updates).length > 0) {
      updateLearningGoal.mutate({
        goalId: goal.id,
        moduleId: module.id,
        data: updates,
      })
    }
  }

  const handleDeleteLearningGoal = (goalId: string) => {
    if (!canEdit) return
    deleteLearningGoal.mutate({ goalId, moduleId: module.id })
  }

  const isGeneratingGoals = generateLearningGoals.isPending

  return (
    <div className="space-y-6">
      {/* Module Information Section */}
      <Card>
        <CardHeader>
          <CardTitle>Module Information</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="module-name">Name</Label>
            <Input
              id="module-name"
              value={module.name}
              onChange={(e) => {
                if (!canEdit) return
                updateModule.mutate({
                  id: module.id,
                  data: { name: e.target.value },
                })
              }}
              placeholder="Module name"
              readOnly={!canEdit}
            />
          </div>

          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <Label htmlFor="module-overview">Overview</Label>
              {canEdit && (
                <Button
                  type="button"
                  variant="outline"
                  size="sm"
                  onClick={handleRegenerateOverview}
                  disabled={generateOverview.isPending}
                >
                  {generateOverview.isPending ? (
                    <>
                      <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                      Generating...
                    </>
                  ) : (
                    <>
                      <Sparkles className="h-4 w-4 mr-2" />
                      Regenerate
                    </>
                  )}
                </Button>
              )}
            </div>
            <Textarea
              id="module-overview"
              value={overview}
              onChange={(e) => setOverview(e.target.value)}
              onBlur={handleSaveOverview}
              placeholder={generateOverview.isPending ? "Generating overview..." : "Enter module overview..."}
              rows={6}
              disabled={generateOverview.isPending || !canEdit}
              readOnly={!canEdit}
            />
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="module-due-date">Due Date</Label>
              <Input
                id="module-due-date"
                type="date"
                value={dueDate}
                onChange={(e) => setDueDate(e.target.value)}
                onBlur={handleSaveDueDate}
                disabled={!canEdit}
                readOnly={!canEdit}
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="module-prerequisites">Prerequisites</Label>
              <Input
                id="module-prerequisites"
                value={prerequisites}
                onChange={(e) => setPrerequisites(e.target.value)}
                onBlur={handleSavePrerequisites}
                placeholder="e.g., CS 101, MATH 201"
                disabled={!canEdit}
                readOnly={!canEdit}
              />
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Learning Goals Section */}
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <CardTitle>Learning Goals</CardTitle>
            {canEdit && (
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={handleRegenerateLearningGoals}
                disabled={isGeneratingGoals}
              >
                {isGeneratingGoals ? (
                  <>
                    <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    <Sparkles className="h-4 w-4 mr-2" />
                    Regenerate
                  </>
                )}
              </Button>
            )}
          </div>
        </CardHeader>
        <CardContent className="space-y-4">
          {isLoadingGoals || isGeneratingGoals ? (
            <div className="flex items-center justify-center py-4 text-muted-foreground">
              <Loader2 className="h-4 w-4 mr-2 animate-spin" />
              {isGeneratingGoals ? 'Generating learning goals...' : 'Loading...'}
            </div>
          ) : learningGoals.length === 0 ? (
            <p className="text-sm text-muted-foreground">
              No learning goals yet. Click &quot;Add Learning Goal&quot; to get started.
            </p>
          ) : (
            <div className="space-y-3">
              {learningGoals.map((goal) => {
                const isExpanded = expandedGoalId === goal.id
                const editing = editingGoals[goal.id]
                return (
                  <div
                    key={goal.id}
                    className={cn(
                      'border rounded-lg overflow-hidden transition-all',
                      isExpanded && 'bg-muted/30'
                    )}
                  >
                    {/* Header row */}
                    <div
                      className={cn(
                        'flex items-center gap-2 p-3 cursor-pointer transition-colors',
                        !isExpanded && 'hover:bg-muted/30'
                      )}
                      onClick={() => setExpandedGoalId(isExpanded ? null : goal.id)}
                    >
                      <ChevronDown
                        className={cn(
                          'h-4 w-4 text-muted-foreground transition-transform flex-shrink-0',
                          isExpanded && 'rotate-180'
                        )}
                      />
                      {isExpanded ? (
                        <Input
                          value={editing?.description ?? goal.description}
                          onChange={(e) =>
                            setEditingGoals((prev) => ({
                              ...prev,
                              [goal.id]: { ...(prev[goal.id] || { description: goal.description, takeaways: goal.takeaways || '', competencies: goal.competencies || '' }), description: e.target.value },
                            }))
                          }
                          onBlur={() => handleUpdateLearningGoal(goal)}
                          onClick={(e) => e.stopPropagation()}
                          placeholder="Learning goal description"
                          className="flex-1"
                          readOnly={!canEdit}
                          disabled={!canEdit}
                        />
                      ) : (
                        <span className="flex-1 text-sm truncate">
                          {editing?.description || goal.description || 'Untitled goal'}
                        </span>
                      )}
                      {canEdit && (
                        <Button
                          type="button"
                          variant="ghost"
                          size="sm"
                          onClick={(e) => {
                            e.stopPropagation()
                            handleDeleteLearningGoal(goal.id)
                          }}
                          className="h-8 w-8 p-0 flex-shrink-0"
                        >
                          <X className="h-4 w-4" />
                        </Button>
                      )}
                    </div>

                    {/* Expanded content: takeaways & competencies */}
                    {isExpanded && (
                      <div className="px-6 pb-4 space-y-4">
                        <div className="space-y-2">
                          <Label className="text-xs font-medium uppercase text-muted-foreground">
                            Takeaways
                          </Label>
                          <Textarea
                            value={editing?.takeaways ?? goal.takeaways ?? ''}
                            onChange={(e) =>
                              setEditingGoals((prev) => ({
                                ...prev,
                                [goal.id]: { ...(prev[goal.id] || { description: goal.description, takeaways: goal.takeaways || '', competencies: goal.competencies || '' }), takeaways: e.target.value },
                              }))
                            }
                            onBlur={() => handleUpdateLearningGoal(goal)}
                            placeholder="Key concepts or skills to be learned..."
                            className="min-h-[60px] resize-none"
                            readOnly={!canEdit}
                            disabled={!canEdit}
                          />
                        </div>
                        <div className="space-y-2">
                          <Label className="text-xs font-medium uppercase text-muted-foreground">
                            Competencies
                          </Label>
                          <Textarea
                            value={editing?.competencies ?? goal.competencies ?? ''}
                            onChange={(e) =>
                              setEditingGoals((prev) => ({
                                ...prev,
                                [goal.id]: { ...(prev[goal.id] || { description: goal.description, takeaways: goal.takeaways || '', competencies: goal.competencies || '' }), competencies: e.target.value },
                              }))
                            }
                            onBlur={() => handleUpdateLearningGoal(goal)}
                            placeholder="Abilities to apply learned concepts..."
                            className="min-h-[60px] resize-none"
                            readOnly={!canEdit}
                            disabled={!canEdit}
                          />
                        </div>
                      </div>
                    )}
                  </div>
                )
              })}
            </div>
          )}
          {canEdit && (
            <Button
              type="button"
              variant="outline"
              onClick={handleAddLearningGoal}
              className="w-full"
              disabled={createLearningGoal.isPending || isGeneratingGoals}
            >
              <Plus className="h-4 w-4 mr-2" />
              Add Learning Goal
            </Button>
          )}
        </CardContent>
      </Card>
    </div>
  )
}
