"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { X } from "lucide-react";
import { AnimatePresence, LayoutGroup, motion } from "framer-motion";

import { Button, IconButton } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { useModuleDraftStore } from "@/lib/stores/module-draft-store";
import { useSourcePolling } from "@/lib/hooks/use-source-polling";
import {
  usePreviewModuleContent,
  useGenerateOverview,
  useGenerateLearningGoals,
  useCreateModule,
} from "@/lib/hooks/use-modules";
import { useBatchDeleteSources, useDeleteSource } from "@/lib/hooks/use-sources";
import { modulesApi } from "@/lib/api/modules";
import { useCoursesStore } from "@/lib/stores/courses-store";

import { ModuleInfoPanel } from "@/components/modules/review/ModuleInfoPanel";
import { LearningGoalsPanel } from "@/components/modules/review/LearningGoalsPanel";
import { FilesSidebar } from "@/components/modules/review/FilesSidebar";
import { DeleteDraftModal } from "@/components/modules/review/DeleteDraftModal";
import { SourceDialog } from "@/components/source/SourceDialog";
import { CreateModuleWizard } from "@/components/modules/CreateModuleWizard";
import { RefinementChat } from "@/components/modules/RefinementChat";
import { UploadStage } from "@/components/modules/review/UploadStage";
import { LearningGoalPreview } from "@/lib/types/api";

type ReviewPhase = "uploading" | "revealed";

export default function ModuleReviewPage() {
  const router = useRouter();
  const {
    pendingSourceIds,
    name,
    overview,
    learningGoals,
    targetCourseId,
    hasGeneratedContent,
    setModuleField,
    setGeneratedContent,
    setDraftModuleId,
    removePendingSource,
    reset,
  } = useModuleDraftStore();

  const { assignModuleToCourse } = useCoursesStore();

  // Polling and mutations
  const {
    allComplete,
    progressPercentage,
    statuses: sourceStatuses,
  } = useSourcePolling(pendingSourceIds);
  const previewContent = usePreviewModuleContent();
  const generateOverview = useGenerateOverview();
  const generateLearningGoals = useGenerateLearningGoals();
  const createModule = useCreateModule();
  const batchDelete = useBatchDeleteSources();
  const deleteSource = useDeleteSource();

  // Local state
  const [phase, setPhase] = useState<ReviewPhase>("uploading");
  const [showDeleteModal, setShowDeleteModal] = useState(false);
  const [showAddFilesDialog, setShowAddFilesDialog] = useState(false);
  const [isConfirming, setIsConfirming] = useState(false);
  const [selectedSourceId, setSelectedSourceId] = useState<string | null>(null);
  const hasAutoGenerated = useRef(false);

  // Track files added after initial upload to trigger regeneration
  const pendingNewFilesRef = useRef<Set<string>>(new Set());
  const previousSourceCountRef = useRef(pendingSourceIds.length);

  // Redirect if no pending sources (user navigated directly to this page)
  useEffect(() => {
    if (pendingSourceIds.length === 0) {
      router.replace("/courses");
    }
  }, [pendingSourceIds.length, router]);

  // Navigation guard - warn about unsaved changes
  useEffect(() => {
    const handleBeforeUnload = (e: BeforeUnloadEvent) => {
      if (pendingSourceIds.length > 0) {
        e.preventDefault();
        e.returnValue =
          "You have unsaved changes. Are you sure you want to leave?";
        return e.returnValue;
      }
    };

    window.addEventListener("beforeunload", handleBeforeUnload);
    return () => {
      window.removeEventListener("beforeunload", handleBeforeUnload);
    };
  }, [pendingSourceIds.length]);

  // Transition to revealed phase after all sources complete (with delay for UX)
  useEffect(() => {
    if (allComplete && phase === "uploading") {
      const timer = setTimeout(() => {
        setPhase("revealed");
      }, 800);
      return () => clearTimeout(timer);
    }
  }, [allComplete, phase]);

  // Auto-generate content when all sources complete
  useEffect(() => {
    if (
      allComplete &&
      !hasGeneratedContent &&
      !hasAutoGenerated.current &&
      !previewContent.isPending &&
      pendingSourceIds.length > 0
    ) {
      hasAutoGenerated.current = true;

      previewContent.mutate(
        { source_ids: pendingSourceIds, name: name || "" },
        {
          onSuccess: (data) => {
            setGeneratedContent(
              data.overview,
              data.learning_goals.map((g, i) => ({
                description: g.description,
                takeaways: g.takeaways || "",
                competencies: g.competencies || "",
                order: i,
              }))
            );
            // Use AI-generated name if user hasn't set one
            if (!name && data.name) {
              setModuleField("name", data.name);
            }
          },
        }
      );
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [
    allComplete,
    hasGeneratedContent,
    pendingSourceIds.length,
    previewContent.isPending,
  ]);

  // Detect when new files are added and track them
  useEffect(() => {
    if (pendingSourceIds.length > previousSourceCountRef.current) {
      const newFiles = pendingSourceIds.slice(previousSourceCountRef.current);
      newFiles.forEach((id) => pendingNewFilesRef.current.add(id));
    }
    previousSourceCountRef.current = pendingSourceIds.length;
  }, [pendingSourceIds.length, pendingSourceIds]);

  // Regenerate content when new files finish processing
  useEffect(() => {
    if (pendingNewFilesRef.current.size === 0) return;
    if (previewContent.isPending) return;

    const newFilesComplete = Array.from(pendingNewFilesRef.current).every(
      (id) =>
        sourceStatuses[id] === "completed" || sourceStatuses[id] === "failed"
    );

    if (newFilesComplete && allComplete) {
      pendingNewFilesRef.current.clear();

      previewContent.mutate(
        { source_ids: pendingSourceIds, name: name || "" },
        {
          onSuccess: (data) => {
            if (data.name) {
              setModuleField("name", data.name);
            }
            setGeneratedContent(
              data.overview,
              data.learning_goals.map((g, i) => ({
                description: g.description,
                takeaways: g.takeaways || "",
                competencies: g.competencies || "",
                order: i,
              }))
            );
          },
        }
      );
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [allComplete, sourceStatuses, previewContent.isPending]);

  // Handle regenerate overview only
  const handleRegenerateOverview = () => {
    if (pendingSourceIds.length === 0) return;

    generateOverview.mutate(
      { source_ids: pendingSourceIds, name: name || "New Module" },
      {
        onSuccess: (data) => {
          setModuleField("overview", data.overview);
        },
      }
    );
  };

  // Handle regenerate learning goals only
  const handleRegenerateLearningGoals = () => {
    if (pendingSourceIds.length === 0) return;

    generateLearningGoals.mutate(
      { source_ids: pendingSourceIds, name: name || "New Module" },
      {
        onSuccess: (data) => {
          setGeneratedContent(
            overview,
            data.learning_goals.map((g, i) => ({
              description: g.description,
              takeaways: g.takeaways || "",
              competencies: g.competencies || "",
              order: i,
            }))
          );
        },
      }
    );
  };

  // Handle cancel/delete draft
  const handleDeleteDraft = async () => {
    try {
      if (pendingSourceIds.length > 0) {
        await batchDelete.mutateAsync(pendingSourceIds);
      }
      reset();
      router.push("/courses");
    } catch (error) {
      console.error("Error deleting draft:", error);
    }
  };

  const handleClose = () => {
    setShowDeleteModal(true);
  };

  // Handle confirm - save module as draft, link sources, then navigate to try-tutor
  const handleConfirm = async () => {
    if (!name.trim()) {
      return;
    }

    setIsConfirming(true);
    try {
      const createdModule = await createModule.mutateAsync({
        name: name.trim(),
        description: overview || undefined,
        course_id: targetCourseId || undefined,
        status: "draft",
      });

      await Promise.allSettled(
        pendingSourceIds.map((sourceId) =>
          modulesApi.addSource(createdModule.id, sourceId)
        )
      );

      for (const goal of learningGoals) {
        await modulesApi.createLearningGoal(createdModule.id, {
          description: goal.description,
          takeaways: goal.takeaways || undefined,
          competencies: goal.competencies || undefined,
          order: goal.order,
        });
      }

      if (overview) {
        await modulesApi.update(createdModule.id, { overview });
      }

      if (targetCourseId) {
        assignModuleToCourse(createdModule.id, targetCourseId);
      }

      setDraftModuleId(createdModule.id);
      router.push(`/modules/${encodeURIComponent(createdModule.id)}/try-tutor`);
    } catch (error: unknown) {
      const axiosErr = error as { response?: { data?: unknown } };
      console.error("Error creating module:", error);
      if (axiosErr?.response?.data) {
        console.error("Server response:", JSON.stringify(axiosErr.response.data));
      }
    } finally {
      setIsConfirming(false);
    }
  };

  const handleRemoveSource = async (sourceIdWithPrefix: string) => {
    const fullId = sourceIdWithPrefix.includes(':')
      ? sourceIdWithPrefix
      : `source:${sourceIdWithPrefix}`;

    setSelectedSourceId(null);
    try {
      await deleteSource.mutateAsync(fullId);
    } catch {
      // ignore — source may already be deleted
    }
    removePendingSource(fullId);

    // Re-trigger generation with remaining sources
    const remaining = pendingSourceIds.filter((id) => id !== fullId);
    if (remaining.length > 0) {
      previewContent.mutate(
        { source_ids: remaining, name: name || "" },
        {
          onSuccess: (data) => {
            setGeneratedContent(
              data.overview,
              data.learning_goals.map((g, i) => ({
                description: g.description,
                takeaways: g.takeaways || "",
                competencies: g.competencies || "",
                order: i,
              }))
            );
            if (!name && data.name) {
              setModuleField("name", data.name);
            }
          },
        }
      );
    }
  };

  const handleAddMore = () => {
    setShowAddFilesDialog(true);
  };

  const handleSourceClick = (sourceId: string) => {
    setSelectedSourceId(sourceId);
  };

  // Per-section pulse state for AI refinement animation
  const [refinePulse, setRefinePulse] = useState({ overview: false, goals: false });
  const refinePulseTimeout = useRef<ReturnType<typeof setTimeout> | null>(null);

  const handleRefinementApply = (newOverview: string, newGoals: LearningGoalPreview[]) => {
    const overviewChanged = newOverview !== overview;
    const goalsChanged =
      newGoals.length !== learningGoals.length ||
      newGoals.some((g, i) => g.description !== learningGoals[i]?.description);

    setGeneratedContent(
      newOverview,
      newGoals.map((g, i) => ({
        description: g.description,
        takeaways: g.takeaways || "",
        competencies: g.competencies || "",
        order: i,
      }))
    );

    if (refinePulseTimeout.current) clearTimeout(refinePulseTimeout.current);
    setRefinePulse({ overview: overviewChanged, goals: goalsChanged });
    refinePulseTimeout.current = setTimeout(
      () => setRefinePulse({ overview: false, goals: false }),
      1600
    );
  };

  const isGeneratingAll = previewContent.isPending;
  const isGeneratingOverview = generateOverview.isPending || isGeneratingAll;
  const isGeneratingGoals = generateLearningGoals.isPending || isGeneratingAll;
  const isGenerating = isGeneratingOverview || isGeneratingGoals;
  const canConfirm = name.trim().length > 0 && !isGenerating && !isConfirming;

  if (pendingSourceIds.length === 0) {
    return null;
  }

  return (
    <div className="flex flex-col h-screen bg-background">
      {/* Header */}
      <header className="flex-shrink-0 flex items-center justify-between px-6 py-4 border-b">
        <div className="flex items-center gap-4">
          <IconButton size="sm" onClick={handleClose} aria-label="Close">
            <X />
          </IconButton>
          <h1 className="font-heading text-[32px] font-medium tracking-[-0.02em] text-primary">
            Create Module {">"} Review and Edit
          </h1>
        </div>
      </header>

      {/* Content */}
      <LayoutGroup>
        <main className="flex-1 min-h-0 overflow-y-auto p-6 flex flex-col">
          <AnimatePresence mode="popLayout" initial={false}>
            {phase === "uploading" ? (
              <motion.div
                key="upload-stage"
                className="flex-1"
                exit={{ opacity: 0, scale: 0.98 }}
                transition={{ duration: 0.35, ease: "easeIn" }}
              >
                <UploadStage
                  sourceIds={pendingSourceIds}
                  sourceStatuses={sourceStatuses}
                  progressPercentage={progressPercentage}
                  onAddMore={handleAddMore}
                  onSourceClick={handleSourceClick}
                />
              </motion.div>
            ) : (
              <motion.div
                key="review-stage"
                className="flex flex-col gap-6"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ duration: 0.2 }}
              >
                <div className="flex gap-6">
                  {/* Left column - Module info */}
                  <motion.div
                    initial={{ opacity: 0, x: -16 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ duration: 0.4, delay: 0.15, ease: "easeOut" }}
                  >
                    <ModuleInfoPanel
                      isGenerating={isGeneratingOverview}
                      onRegenerateOverview={handleRegenerateOverview}
                      isPulsingOverview={refinePulse.overview}
                    />
                  </motion.div>

                  {/* Center column - Learning goals */}
                  <motion.div
                    initial={{ opacity: 0, y: 16 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.4, delay: 0.25, ease: "easeOut" }}
                    className="flex-1 min-w-0 flex flex-col min-h-0"
                  >
                    <LearningGoalsPanel
                      isGenerating={isGeneratingGoals}
                      onRegenerateLearningGoals={handleRegenerateLearningGoals}
                      isPulsingGoals={refinePulse.goals}
                    />
                  </motion.div>

                  {/* Right column - Files sidebar (thumbnails animate here via layoutId) */}
                  <motion.div
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    transition={{ duration: 0.3, delay: 0.1 }}
                  >
                    <FilesSidebar
                      sourceIds={pendingSourceIds}
                      sourceStatuses={sourceStatuses}
                      onAddMore={handleAddMore}
                      onSourceClick={handleSourceClick}
                    />
                  </motion.div>
                </div>

                {/* Refinement Chat */}
                {allComplete && hasGeneratedContent && (
                  <motion.div
                    className="flex-shrink-0"
                    initial={{ opacity: 0, y: 12 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.4, delay: 0.4 }}
                  >
                    <RefinementChat
                      currentOverview={overview || ""}
                      currentGoals={learningGoals.map((g) => ({
                        description: g.description,
                        takeaways: g.takeaways || "",
                        competencies: g.competencies || "",
                      }))}
                      onApplyChanges={handleRefinementApply}
                      sourceIds={pendingSourceIds}
                    />
                  </motion.div>
                )}
              </motion.div>
            )}
          </AnimatePresence>
        </main>
      </LayoutGroup>

      {/* Footer - hidden during upload phase, slides in on reveal */}
      <AnimatePresence>
        {phase === "revealed" && (
          <motion.footer
            className="flex-shrink-0 px-6 py-4 border-t bg-background"
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.35, delay: 0.1, ease: "easeOut" }}
          >
            <div className="flex items-center gap-4">
              <div className="flex-1">
                <Progress
                  value={allComplete ? 100 : progressPercentage}
                  className="h-2"
                />
              </div>

              <span className="font-sans text-[14px] font-normal text-teal-800 w-12 text-right">
                {allComplete ? 100 : progressPercentage}%
              </span>

              <Button
                variant="accent"
                onClick={handleConfirm}
                disabled={!canConfirm}
              >
                {isConfirming ? "Creating..." : "Try Tutor"}
              </Button>
            </div>
          </motion.footer>
        )}
      </AnimatePresence>

      {/* Delete draft confirmation modal */}
      <DeleteDraftModal
        open={showDeleteModal}
        onOpenChange={setShowDeleteModal}
        onConfirm={handleDeleteDraft}
        isDeleting={batchDelete.isPending}
      />

      {/* Source detail dialog */}
      <SourceDialog
        open={selectedSourceId !== null}
        onOpenChange={(open) => {
          if (!open) setSelectedSourceId(null);
        }}
        sourceId={selectedSourceId}
        onRemove={handleRemoveSource}
      />

      {/* Add more files — reuses the create-module wizard without resetting state */}
      <CreateModuleWizard
        open={showAddFilesDialog}
        onOpenChange={setShowAddFilesDialog}
        addMoreMode
      />
    </div>
  );
}
